#Each new term in the Fibonacci sequence is generated by 
#adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not 
#exceed four million, find the sum of the even-valued terms.

def main():

  t1 = 1
  t2 = 2
  val = 0
  evensSum = 2

  while (val < 4000000):
    val = sumTerms(t1, t2)
    if (val%2 ==0):
      evensSum += val
  
    t1 = t2
    t2 = val

    print evensSum

    




def sumTerms(num1, num2):
  return (num1+num2)






if __name__ == "__main__":
	main()